apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  #replicas: 1
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-web-app
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
